{
 "title": "Fluent Bit - Summer Series 2023",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Fluent Bit Input Bytes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Fluent Bit Input Record",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Storage chunks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fluentbit_storage_chunks" }
   ]
  },
  {
   "title": "Input Storage chunks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(fluentbit_input_storage_chunks)"
    }
   ]
  },
  {
   "title": "Busy connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluentbit_output_upstream_busy_connections"
    }
   ]
  },
  {
   "title": "Total connections",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluentbit_output_upstream_total_connections"
    }
   ]
  },
  {
   "title": "Fluent Bit Output Bytes",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Fluent Bit Output Records",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Input bytes",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(fluentbit_input_bytes_total[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Input records",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(fluentbit_input_records_total[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Output bytes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_bytes_total[$__rate_interval])",
     "legendFormat": "Output {{name}}"
    }
   ]
  },
  {
   "title": "Output records",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(fluentbit_output_proc_records_total[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Input + Output bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_bytes_total[10s]))",
     "legendFormat": "Input {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_bytes_total[10s]))",
     "legendFormat": "Output {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Input + Output records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(fluentbit_input_records_total[$__rate_interval]))",
     "legendFormat": "Input {{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(rate(fluentbit_output_proc_records_total[$__rate_interval]))",
     "legendFormat": "Output {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "targets": [
    { "expr": "fluentbit_storage_chunks", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "fluentbit_output_upstream_total_connections",
     "legendFormat": "Total connections"
    },
    {
     "expr": "fluentbit_output_upstream_busy_connections",
     "legendFormat": "Busy connections"
    }
   ]
  },
  {
   "title": "Output errors total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "rate(fluentbit_output_errors_total[10s])",
     "legendFormat": "Output {{name}}"
    }
   ]
  },
  {
   "title": "Output retried failed total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "fluentbit_output_retries_failed_total",
     "legendFormat": "Output {{name}}"
    }
   ]
  },
  {
   "title": "Output retried errors total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "fluentbit_output_retried_records_total",
     "legendFormat": "Output {{name}}"
    }
   ]
  },
  {
   "title": "Output dropped records total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "fluentbit_output_dropped_records_total",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Input + Output records TOTAL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "targets": [
    { "expr": "fluentbit_input_records_total", "legendFormat": "Input {{name}}" },
    {
     "expr": "fluentbit_output_proc_records_total",
     "legendFormat": "Output {{name}}"
    }
   ]
  },
  {
   "title": "Filter dropped records",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "fluentbit_filter_drop_records_total",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_rss{namespace=\"issue-poc\"})",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_user_seconds_total{namespace=\"issue-poc\"}[$__rate_interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memrb dropped bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "targets": [
    {
     "expr": "rate(fluentbit_input_memrb_dropped_bytes[10s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memrb dropped Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "targets": [
    {
     "expr": "rate(fluentbit_input_memrb_dropped_chunks[10s])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Input + Output records TOTAL diff",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fluentbit_output_proc_records_total",
     "legendFormat": "Output {{name}}"
    },
    { "expr": "fluentbit_input_records_total", "legendFormat": "Input {{name}}" }
   ]
  },
  {
   "title": "Input + Output records TOTAL diff",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "fluentbit_output_proc_records_total",
     "legendFormat": "Output {{name}}"
    },
    { "expr": "fluentbit_input_records_total", "legendFormat": "Input {{name}}" }
   ]
  }
 ]
}